spring:
  application:
    name: metric_and_logs

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
        step: 5s
    scrape_configs:
      - job_name: 'spring-boot-app'
        static_configs:
          - targets: [ 'localhost:8080' ]
